version: '3'
services:
  documentserver:
    image:  onlyoffice/documentserver-ie:5.6.4.20
    ports:
      - 3000:80
  nginx:
    image: nginx
    ports:
      - 4200:80
    volumes: 
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf